# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gzzb3',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('gz1', models.FloatField(null=True, db_column=b'\xe6\x97\xb6\xe9\x97\xb4', blank=True)),
                ('gz2', models.FloatField(null=True, db_column=b'\xe4\xbb\xa3\xe6\x89\xa3\xe7\xa8\x8e', blank=True)),
                ('gz3', models.FloatField(null=True, db_column=b'\xe5\xae\x9e\xe9\x99\x85\xe6\x89\xa3\xe7\xa8\x8e', blank=True)),
                ('gz4', models.FloatField(null=True, db_column=b'\xe5\xae\x9e\xe5\x8f\x91\xe5\xb7\xa5\xe8\xb5\x84', blank=True)),
                ('gz5', models.FloatField(null=True, db_column=b'\xe5\xae\x9e\xe5\x8f\x91\xe5\xb7\xa5\xe8\xb5\x842', blank=True)),
                ('gz6', models.FloatField(null=True, db_column=b'\xe5\xba\x94\xe5\x8f\x91\xe5\xb7\xa5\xe8\xb5\x84\xe6\x80\xbb', blank=True)),
                ('gz7', models.FloatField(null=True, db_column=b'\xe5\xae\x9e\xe5\x8f\x91\xe5\xb7\xa5\xe8\xb5\x84\xe6\x80\xbb', blank=True)),
                ('gz8', models.CharField(max_length=255, null=True, db_column=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe5\x8f\xb7\xe7\xa0\x81', blank=True)),
                ('gz9', models.FloatField(null=True, db_column=b'\xe5\x91\x98\xe5\xb7\xa5\xe7\xbc\x96\xe5\x8f\xb7', blank=True)),
                ('gz10', models.CharField(max_length=255, null=True, db_column=b'\xe9\x93\xb6\xe8\xa1\x8c\xe5\x8f\xb7', blank=True)),
                ('gz11', models.CharField(max_length=255, null=True, db_column=b'\xe4\xb8\x8a\xe6\xb5\xb7\xe7\xbc\xb4\xe7\xba\xb3\xe4\xb8\xaa\xe7\xa8\x8e', blank=True)),
                ('gz12', models.FloatField(null=True, db_column=b'\xe8\xa1\xa82\xe7\xbb\xa9\xe6\x95\x88', blank=True)),
                ('gz13', models.FloatField(null=True, db_column=b'\xe8\xa1\xa81\xe7\xbb\xa9\xe6\x95\x88', blank=True)),
                ('gz14', models.FloatField(null=True, db_column=b'\xe6\x99\xae\xe9\x80\x9a\xe5\x8a\xa0\xe7\x8f\xad\xe8\xb4\xb9', blank=True)),
                ('gz15', models.FloatField(null=True, db_column=b'2\xe5\x80\x8d\xe5\x8a\xa0\xe7\x8f\xad\xe8\xb4\xb9', blank=True)),
                ('gz16', models.FloatField(null=True, db_column=b'\xe6\xb3\x95\xe5\xae\x9a\xe5\x8a\xa0\xe7\x8f\xad\xe8\xb4\xb9', blank=True)),
                ('gz17', models.FloatField(null=True, db_column=b'\xe7\xa4\xbe\xe4\xbf\x9d', blank=True)),
                ('gz18', models.FloatField(null=True, db_column=b'\xe8\xa1\xa81\xe7\x97\x85\xe5\x81\x87\xe6\x89\xa3', blank=True)),
                ('gz19', models.FloatField(null=True, db_column=b'\xe8\xa1\xa82\xe7\x97\x85\xe5\x81\x87\xe6\x89\xa3', blank=True)),
                ('gz20', models.FloatField(null=True, db_column=b'\xe8\xa1\xa81\xe4\xba\x8b\xe5\x81\x87\xe6\x89\xa3', blank=True)),
                ('gz21', models.FloatField(null=True, db_column=b'\xe8\xa1\xa82\xe4\xba\x8b\xe5\x81\x87\xe6\x89\xa3', blank=True)),
                ('gz22', models.FloatField(null=True, db_column=b'\xe8\xa1\xa81\xe8\xbd\xae\xe4\xbc\x91\xe6\x89\xa3', blank=True)),
                ('gz23', models.FloatField(null=True, db_column=b'\xe8\xa1\xa82\xe8\xbd\xae\xe4\xbc\x91\xe6\x89\xa3', blank=True)),
                ('gz24', models.FloatField(null=True, db_column=b'\xe5\x85\xb6\xe4\xbb\x96\xe6\x89\xa3', blank=True)),
                ('gz25', models.FloatField(null=True, db_column=b'\xe8\xa1\xa82\xe6\x89\xa3', blank=True)),
                ('gz26', models.FloatField(null=True, db_column=b'\xe7\xbb\xa9\xe6\x95\x88\xe5\xa2\x9e\xe5\x87\x8f', blank=True)),
                ('gz27', models.FloatField(null=True, db_column=b'\xe8\xb5\xb7\xe5\xbe\x81\xe7\x82\xb9', blank=True)),
                ('gz28', models.FloatField(null=True, db_column=b'\xe6\xb3\x95\xe5\xae\x9a\xe5\x92\x8c2\xe5\x80\x8d\xe5\x8a\xa0\xe7\x8f\xad\xe8\xb4\xb9', blank=True)),
                ('gz29', models.FloatField(null=True, db_column=b'\xe8\xbd\xae\xe4\xbc\x91\xe5\x92\x8c\xe5\x85\xb6\xe4\xbb\x96\xe6\x89\xa3', blank=True)),
                ('gz30', models.FloatField(null=True, db_column=b'\xe7\x97\x85\xe4\xba\x8b\xe5\x81\x87\xe6\x89\xa3', blank=True)),
                ('gz31', models.FloatField(null=True, db_column=b'\xe5\xba\x94\xe5\x8f\x91\xe5\xb7\xa5\xe8\xb5\x84', blank=True)),
                ('gz32', models.FloatField(null=True, db_column=b'\xe7\xba\xb3\xe7\xa8\x8e\xe5\xb7\xa5\xe8\xb5\x84', blank=True)),
                ('gz33', models.CharField(max_length=255, null=True, db_column=b'\xe5\x9f\xba\xe5\x9c\xb0', blank=True)),
                ('gz34', models.CharField(max_length=255, null=True, db_column=b'\xe5\x8d\x95\xe4\xbd\x8d\xe5\x8f\xb7', blank=True)),
                ('gz35', models.FloatField(null=True, db_column=b'\xe5\x8a\xa0\xe7\x8f\xad\xe5\x9f\xba\xe6\x95\xb0', blank=True)),
                ('gz36', models.CharField(max_length=255, null=True, db_column=b'\xe5\x8d\x95\xe4\xbd\x8d', blank=True)),
                ('gz37', models.CharField(max_length=255, null=True, db_column=b'\xe5\xb7\xa5\xe5\x8f\xb7', blank=True)),
                ('gz38', models.CharField(max_length=255, null=True, db_column=b'\xe5\xa7\x93\xe5\x90\x8d', blank=True)),
                ('gz39', models.FloatField(null=True, db_column=b'\xe7\xbc\xba\xe5\x8b\xa4', blank=True)),
                ('gz40', models.FloatField(null=True, db_column=b'\xe5\x8a\xa0\xe7\x8f\xad\xe6\x97\xa5', blank=True)),
                ('gz41', models.FloatField(null=True, db_column=b'\xe4\xba\x8c\xe5\x80\x8d\xe6\x97\xa5', blank=True)),
                ('gz42', models.FloatField(null=True, db_column=b'\xe5\x87\xba\xe5\x8b\xa4', blank=True)),
                ('gz43', models.FloatField(null=True, db_column=b'\xe6\xb3\x95\xe5\xae\x9a\xe6\x97\xa5', blank=True)),
                ('gz44', models.FloatField(null=True, db_column=b'\xe7\x97\x85\xe5\x81\x87\xe6\x97\xa5', blank=True)),
                ('gz45', models.CharField(max_length=255, null=True, db_column=b'\xe7\x97\x85\xe5\x81\x873\xe6\x9c\x88', blank=True)),
                ('gz46', models.FloatField(null=True, db_column=b'\xe5\x85\xb6\xe4\xbb\x96\xe6\x97\xa5', blank=True)),
                ('gz47', models.FloatField(null=True, db_column=b'\xe8\xbd\xae\xe4\xbc\x91\xe6\x97\xa5', blank=True)),
                ('gz48', models.FloatField(null=True, db_column=b'\xe5\xb7\xa5\xe8\xb5\x84\xe6\xa0\x87\xe5\x87\x86', blank=True)),
                ('gz49', models.FloatField(null=True, db_column=b'\xe5\xb2\x97\xe4\xbd\x8d\xe5\xb7\xa5\xe8\xb5\x84', blank=True)),
                ('gz50', models.FloatField(null=True, db_column=b'\xe7\xbb\xa9\xe6\x95\x88\xe5\xb7\xa5\xe8\xb5\x84', blank=True)),
                ('gz51', models.FloatField(null=True, db_column=b'\xe7\xbb\xa9\xe6\x95\x88\xe5\xa2\x9e\xe5\x87\x8f1', blank=True)),
                ('gz52', models.FloatField(null=True, db_column=b'\xe7\xbb\xa9\xe6\x95\x88\xe5\xa2\x9e\xe5\x87\x8f2', blank=True)),
                ('gz53', models.FloatField(null=True, db_column=b'\xe8\x81\x8c\xe5\x8a\xa1', blank=True)),
                ('gz54', models.FloatField(null=True, db_column=b'\xe9\xa9\xbb\xe5\xb2\x9b', blank=True)),
                ('gz55', models.FloatField(null=True, db_column=b'\xe5\xb7\xa5\xe9\xbe\x84', blank=True)),
                ('gz56', models.FloatField(null=True, db_column=b'\xe4\xbc\x99\xe9\xa3\x9f\xe8\xa1\xa5\xe8\xb4\xb4', blank=True)),
                ('gz57', models.FloatField(null=True, db_column=b'\xe4\xb8\xad\xe5\xa4\x9c\xe7\x8f\xad\xe6\xb4\xa5\xe8\xb4\xb4', blank=True)),
                ('gz58', models.FloatField(null=True, db_column=b'\xe8\x8a\x82\xe6\x97\xa5\xe8\xb4\xb9', blank=True)),
                ('gz59', models.FloatField(null=True, db_column=b'\xe7\xbb\xbc\xe5\x90\x88\xe6\xa0\x8f1', blank=True)),
                ('gz60', models.FloatField(null=True, db_column=b'\xe7\xbb\xbc\xe5\x90\x88\xe6\xa0\x8f2', blank=True)),
                ('gz61', models.FloatField(null=True, db_column=b'\xe6\xb0\xb4\xe7\x94\xb5\xe8\xb4\xb9', blank=True)),
                ('gz62', models.FloatField(null=True, db_column=b'\xe5\x85\xbb\xe8\x80\x81\xe8\xb4\xb9', blank=True)),
                ('gz63', models.FloatField(null=True, db_column=b'\xe5\x8c\xbb\xe7\x96\x97', blank=True)),
                ('gz64', models.FloatField(null=True, db_column=b'\xe5\xa4\xb1\xe4\xbf\x9d', blank=True)),
                ('gz65', models.FloatField(null=True, db_column=b'\xe5\x85\xac\xe7\xa7\xaf\xe9\x87\x91', blank=True)),
                ('gz66', models.FloatField(null=True, db_column=b'\xe6\x89\xa3\xe5\x8f\x91', blank=True)),
                ('gz67', models.FloatField(null=True, db_column=b'\xe9\xa5\xad\xe8\xb4\xb4\xe5\x9f\xba\xe6\x95\xb0', blank=True)),
                ('gz68', models.CharField(max_length=255, null=True, db_column=b'\xe5\x88\x86\xe7\xb1\xbb', blank=True)),
                ('gz69', models.FloatField(null=True, db_column=b'\xe9\x80\x9a\xe8\xae\xaf\xe8\xb4\xb9', blank=True)),
                ('gz70', models.CharField(max_length=255, null=True, db_column=b'\xe5\xb2\x97\xe4\xbd\x8d', blank=True)),
                ('gz71', models.CharField(max_length=255, null=True, db_column=b'\xe5\xad\xa6\xe5\x8e\x86', blank=True)),
                ('gz72', models.CharField(max_length=255, null=True, db_column=b'\xe5\x85\xa5\xe5\x8f\xb8\xe6\x97\xb6\xe9\x97\xb4', blank=True)),
                ('gz73', models.CharField(max_length=255, null=True, db_column=b'\xe5\xae\xb6\xe5\xba\xad\xe4\xbd\x8f\xe5\x9d\x80', blank=True)),
                ('gz74', models.CharField(max_length=255, null=True, db_column=b'\xe8\xbd\xac\xe6\xad\xa3\xe6\x97\xa5\xe6\x9c\x9f', blank=True)),
                ('gz75', models.FloatField(null=True, db_column=b'\xe6\x80\xa7\xe5\x88\xab', blank=True)),
                ('gz76', models.CharField(max_length=255, null=True, db_column=b'\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7', blank=True)),
                ('gz77', models.CharField(max_length=255, null=True, db_column=b'\xe7\xa4\xbe\xe4\xbf\x9d\xe7\xbc\x96\xe5\x8f\xb7', blank=True)),
                ('gz78', models.CharField(max_length=255, null=True, db_column=b'\xe5\x85\xac\xe7\xa7\xaf\xe9\x87\x91\xe7\xbc\x96\xe5\x8f\xb7', blank=True)),
                ('gz79', models.FloatField(null=True, db_column=b'\xe5\xad\xa6\xe5\x8e\x86\xe8\xa1\xa5\xe8\xb4\xb4', blank=True)),
                ('gz80', models.FloatField(null=True, db_column=b'\xe8\x81\x8c\xe7\xa7\xb0\xe8\xa1\xa5\xe8\xb4\xb4', blank=True)),
                ('gz81', models.FloatField(null=True, db_column=b'\xe7\x89\xb9\xe6\x8a\x80\xe8\xa1\xa5\xe8\xb4\xb4', blank=True)),
                ('gz82', models.FloatField(null=True, db_column=b'\xe5\xb2\x97\xe4\xbd\x8d\xe8\xa1\xa5\xe8\xb4\xb4', blank=True)),
                ('gz83', models.FloatField(null=True, db_column=b'\xe6\xb4\xa5\xe8\xb4\xb4\xe5\x90\x88\xe8\xae\xa1', blank=True)),
                ('gz84', models.CharField(max_length=255, null=True, db_column=b'\xe5\xb7\xa5\xe8\xb5\x84\xe5\x88\xb6', blank=True)),
            ],
            options={
                'db_table': 'gzzb3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mima',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('mimabh', models.CharField(max_length=255, null=True, db_column=b'\xe5\x91\x98\xe5\xb7\xa5\xe7\xbc\x96\xe5\x8f\xb7', blank=True)),
                ('mimagh', models.CharField(max_length=255, null=True, db_column=b'\xe5\xb7\xa5\xe5\x8f\xb7', blank=True)),
                ('mimaxm', models.CharField(max_length=255, null=True, db_column=b'\xe5\xa7\x93\xe5\x90\x8d', blank=True)),
                ('mimasfzh', models.CharField(max_length=255, null=True, db_column=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe5\x8f\xb7', blank=True)),
                ('mimayhkh', models.CharField(max_length=255, null=True, db_column=b'\xe9\x93\xb6\xe8\xa1\x8c\xe5\x8d\xa1\xe5\x8f\xb7', blank=True)),
                ('mimamm', models.CharField(max_length=255, null=True, db_column=b'\xe5\xaf\x86\xe7\xa0\x81', blank=True)),
            ],
            options={
                'db_table': 'mima',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=40, db_column=b'name'),
        ),
    ]
